name: Build
on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:
env:
  image: ghcr.io/hecto-drone/my-service
jobs:
  deploy-onboard:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: hecto-drone/docker-build@v1
        with:
          image: ${{ env.image }}
          build-for: 'onboard'

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: hecto-drone/docker-build@v1
        with:
          image: ${{ env.image }}
          build-for: 'server'